services:
  app:
    build: .
    container_name: jira_app
    restart: unless-stopped
    ports:
      - "127.0.0.1:5882:8080"
    env_file:
      - .env.local
    depends_on:
      - postgres
    volumes:
      - jira_app_uploads:/app/public/uploads
      - jira_app_uploads_tmp:/app/uploads

  postgres:
    image: postgres:16-alpine
    container_name: jira_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: jirauser
      POSTGRES_PASSWORD: "Neutara@2024"
      POSTGRES_DB: jiradb
    ports:
      - "127.0.0.1:5434:5432"
    volumes:
      - jira_postgres_data:/var/lib/postgresql/data

volumes:
  jira_postgres_data:
  jira_app_uploads:
  jira_app_uploads_tmp:
